name: sdk-ci

on:
  push:
    paths:
      - "**"
  pull_request:
    paths:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: @veya/sdk
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm test
      - run: npm run lint
      - run: npm run build
